# Introduction to Numpy

In [1]:
import numpy as np
import pandas as pd

__numpy.array (object, dtype = none, copy = true, order = none, subok = false, ndmin = 0)__

- object: any object that exposes the array interface method restores the array, or anything (nesting)
- dtype: data type, optional
- copy: Optional. By default (true), the object is copied
- order: C (major line) or F (main column) or A (whatever) (default)
- subok: By default, the returned array is forced to become a basic class array. If true, the sub-class will be given
- ndimin: Determine the minimum dimensions of the array produced

#### Example 1
Enter the integer value or value with any data type as needed

In [2]:
arr = np.array([1,2,3])

In [3]:
print(arr)

[1 2 3]


In [4]:
arr[2]

np.int64(3)

#### Example 2
2-dimensional array

In [5]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


# Array data type

#### Example 1 
Array with Integer Data Type

In [6]:
print(a.dtype)
print(arr.dtype)

int64
int64


#### Example 2 
data type with unicode string

In [7]:
arr_1 = np.array(['rambutan', 'apel', 'jeruk'])
print(arr_1.dtype)

<U8


In [8]:
arr_1 = np.array(['r', 'a', 'j'])
print(arr_1.dtype)

<U1


#### Example 3 
Defined data type

In [9]:
arr_2 = np.array([1, 2, 3, 4], dtype='S')

In [10]:
print(arr_2)

[b'1' b'2' b'3' b'4']


In [11]:
print(arr_2.dtype)

|S1


#### Example 4 
changed data type

In [12]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

In [13]:
print(newarr)

[1 2 3]


In [14]:
print(newarr.dtype)

int32


In [15]:
print(arr.dtype)

float64


Make an array of existing data \
conversion list to ndarray

In [16]:
x = [1, 2, 3, 4, 5]
print(type(x))
p = np.asarray(x)
print(p.dtype)
print(x)
print(p)

<class 'list'>
int64
[1, 2, 3, 4, 5]
[1 2 3 4 5]


#### Example 2
Conversion list becomes an array with defined data types

In [17]:
x = [1, 2, 3, 4, 5]
print(type(x))

<class 'list'>


In [18]:
x = np.asarray(x, dtype='f')
print(x.dtype)
print(x)

float32
[1. 2. 3. 4. 5.]


### Task 1:
- Create two tuple variables that contain numbers
- Enter the two variable tuples into the data list variable
- The conversion list is an array numpy

In [23]:
# Answer
tuple_numbers = ((919, 2019), (2839, 333))
print(type(tuple_numbers))

<class 'tuple'>


In [24]:
numpy_numbers = np.array(tuple_numbers)
print(numpy_numbers.dtype)

int64


In [25]:
print(type(numpy_numbers))

<class 'numpy.ndarray'>


* Creating a range of values using numpy:
* Creating a dataframe using random and deterministic ranges\
__numpy.arange(start, stop, step, dtype)__

In [26]:
z = np.arange(0, 1, 0.1, dtype='f')
x = np.arange(1,11, 1)
y = np.arange(10,20, 1)

In [27]:
print(z)
print(x)
print(y)
print("-"*100)

[0.         0.1        0.2        0.3        0.4        0.5
 0.6        0.7        0.8        0.90000004]
[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14 15 16 17 18 19]
----------------------------------------------------------------------------------------------------


In [28]:
pd.DataFrame({'z' : z, 'x' : x, 'y' : y})

z   x   y
0  0.0   1  10
1  0.1   2  11
2  0.2   3  12
3  0.3   4  13
4  0.4   5  14
5  0.5   6  15
6  0.6   7  16
7  0.7   8  17
8  0.8   9  18
9  0.9  10  19

### Other Common Operations in Numpy

make an array with a value of 1 in numpy

In [29]:
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


make an array with a value of 0 on numpy

In [30]:
x = np.zeros((2,2))
print(x)

[[0. 0.]
 [0. 0.]]


In [31]:
x = np.full((3,4), 0.72)
print(x)

[[0.72 0.72 0.72 0.72]
 [0.72 0.72 0.72 0.72]
 [0.72 0.72 0.72 0.72]]


In [32]:
x = np.random.rand(5,4)
print(x)

[[0.68105354 0.29757076 0.04559252 0.12530146]
 [0.0059165  0.99349808 0.8330163  0.95734394]
 [0.47971531 0.52720428 0.42886462 0.04910714]
 [0.02279376 0.72207289 0.16333348 0.05888217]
 [0.00222333 0.10624683 0.21074111 0.56568967]]


In [33]:
pd.DataFrame(x, columns=['x', 'y', 'z','w'])

x         y         z         w
0  0.681054  0.297571  0.045593  0.125301
1  0.005916  0.993498  0.833016  0.957344
2  0.479715  0.527204  0.428865  0.049107
3  0.022794  0.722073  0.163333  0.058882
4  0.002223  0.106247  0.210741  0.565690

### Task again
* Task 1: Generate Random Array using Np.random.rand with the number of row 3 and the number of columns 4 and enter into the dataframe
* Task 2: Generate array with a value of one and zero which has rows of 5 and 6 columns in two different variables then conversion to dataframe and cum both

In [34]:
# Task 1
acak_numpy = np.random.rand(3,4)
print(acak_numpy)

[[0.5417021  0.37799332 0.9809965  0.58830181]
 [0.29210001 0.7529362  0.38652697 0.10442226]
 [0.669327   0.7353027  0.25355864 0.02115131]]


In [35]:
pd.DataFrame(acak_numpy,columns=["A","B","C","D"])

A         B         C         D
0  0.541702  0.377993  0.980997  0.588302
1  0.292100  0.752936  0.386527  0.104422
2  0.669327  0.735303  0.253559  0.021151

In [36]:
# Task 2
array_ones = np.ones((5, 6), dtype=int)   # Array 5x6 with all values 1
array_zeros = np.zeros((5, 6), dtype=int) # Array 5x6 with all values 0

Conversion to dataframe

In [37]:
df_ones = pd.DataFrame(array_ones, columns=[f"C{i+1}" for i in range(6)])
df_zeros = pd.DataFrame(array_zeros, columns=[f"C{i+1}" for i in range(6)])

Combine vertically (row) → axis = 0

In [38]:
df_concat = pd.concat([df_ones, df_zeros], axis=0, ignore_index=True)

In [39]:
df_concat

C1  C2  C3  C4  C5  C6
0   1   1   1   1   1   1
1   1   1   1   1   1   1
2   1   1   1   1   1   1
3   1   1   1   1   1   1
4   1   1   1   1   1   1
5   0   0   0   0   0   0
6   0   0   0   0   0   0
7   0   0   0   0   0   0
8   0   0   0   0   0   0
9   0   0   0   0   0   0

# Slicing and indexing

## Field Access and Basic Indexing

#### Example 1 
single index, field index

In [40]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [41]:
b = a[5]
print(b)

5


#### Example 2

In [42]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
s = slice(2,7,2)
print(a[s])

[2 4 6]


In [44]:
print(a[slice(1,8,3)])

[1 4 7]


#### Example 3

In [45]:
a = np.arange(10)
b = a[2:7:2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


#### Example 4 
Slicing Index Only by using the Start Parameter

In [46]:
a = np.arange(10)
print(a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


#### Example 5 
Slicing Using Start and Stop Index

In [47]:
a = np.arange(10)
print(a)
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


#### Example 6 
slicing on 2-dimensional array

In [48]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

# Slice items start from an index
print('Slice Array from Index A [1:]')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Slice Array from Index A [1:]
[[3 4 5]
 [4 5 6]]


#### Example 7 
using __ellipsis()__

In [49]:
a = np.array([[1,2,3],
              [3,4,5],
              [4,5,6]])

print('Our array:')
print(a)
print('\ n')

# This returns the item in the second column of the main array
print('Items from the second column:')
print(a[...,1])
print('\ n')

# Slice All items from the second row
print('Items from the second row:')
print(a[1,...])
print('\ n')

# we will slice items from column 1 and so on
print('Items from column 1 and so on:')
print(a[...,1:])


Our array:
[[1 2 3]
 [3 4 5]
 [4 5 6]]
\ n
Items from the second column:
[2 4 5]
\ n
Items from the second row:
[3 4 5]
\ n
Items from column 1 and so on:
[[2 3]
 [4 5]
 [5 6]]


### Case Study
1. Create a 2-dimensional array with shape=(3,4)
2. Index by taking items from the second row and so on until the last row.
3. Index by taking items from columns 1 and 2.

In [50]:
array_2d = np.array([[10, 20, 30, 40],
                     [50, 60, 70, 80],
                     [90, 100, 110, 120]])

print("Array 2D (3x4):")
print(array_2d)

Array 2D (3x4):
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [51]:
end_row2 = array_2d[1:]  # Take the 2nd row to the end (index 1 to finish)
print("Row second to last:")
print(end_row2)

Row second to last:
[[ 50  60  70  80]
 [ 90 100 110 120]]


In [53]:
col_1_2 = array_2d[:, 0:2]  # Take all rows, columns 1 and 2nd (index 0 and 1)
print("Column 1 and 2 of all rows:")
print(col_1_2)

Column 1 and 2 of all rows:
[[ 10  20]
 [ 50  60]
 [ 90 100]]


## Advance Indexing

### Integer Indexing

#### example 1
accessing elements of a 2-dimensional array by specifying the copied rows and columns

In [54]:
x = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [55]:
y = x[[0,1,2], [0,1,1]]
print(y)

[1 4 6]


#### example 2
accessing elements of a 2-dimensional array by specifying the copied rows and columns

In [56]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])

print('Original Array:')
print(x)
print("")
rows = np.array([[0,0],[3,3]]) # The first and fourth lines
cols = np.array([[0,2],[0,2]]) # First and third columns
y = x[rows,cols]

print('Results of the integer index:')
print(y)

Original Array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Results of the integer index:
[[ 0  2]
 [ 9 11]]


#### Example 3

In [58]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])

print('Original Array:')
print(x)

# slicing
z = x[1:4,1:3]

print('After, the results of the array became:')
print(z)

# Using Advanced Index for Column
y = x[1:4,[1,2]]

print('Slicing with the Advance Index for Column:')
print(y)

Original Array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After, the results of the array became:
[[ 4  5]
 [ 7  8]
 [10 11]]
Slicing with the Advance Index for Column:
[[ 4  5]
 [ 7  8]
 [10 11]]


## Boolean Indexing

#### Example 1
take elements with the Boolean index (condition)

In [60]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])

print('Original Array:')
print(x)

# Will be printed more than 5 elements
print('Elements larger than 5:')
print(x[x > 5])

Original Array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Elements larger than 5:
[ 6  7  8  9 10 11]


#### Example 2

In [61]:
a = np.array([np.nan, 1,2,np.nan,3,4,5])
print(a[np.isnan(a)])

[nan nan]


#### Example 3

In [62]:
a = np.array([1, 2+6j, 5, 3.5+5j])
print(a[~np.iscomplex(a)])
print(a[np.iscomplex(a)])

[1.+0.j 5.+0.j]
[2. +6.j 3.5+5.j]


### Case Study
1. Create a 2-dimensional array with shape=(3,4) containing a mix of complex, nan, and integer values.
2. Retrieve elements using Boolean indices for integers, nan, and complex values.

In [63]:
# Making Complex, NaN, and Integer Mixed Array
array_mixed = np.array([
    [1, 2+3j, np.nan, 4],
    [5, 6, 7+1j, np.nan],
    [8+0j, 9, 10, np.nan]
], dtype=object)

print("Mixed Array:")
print(array_mixed)

Mixed Array:
[[1 (2+3j) nan 4]
 [5 6 (7+1j) nan]
 [(8+0j) 9 10 nan]]


Then an element will be taken with the Boolean index for each type

Only integer

In [64]:
# Create a mask for integers
mask_int = np.vectorize(lambda x: isinstance(x, int))(array_mixed)
print("Integer element:")
print(array_mixed[mask_int])

Integer element:
[1 4 5 6 9 10]


Only NaN

In [65]:
# Mask for nan
mask_nan = np.vectorize(lambda x: isinstance(x, float) and np.isnan(x))(array_mixed)
print("NaN element:")
print(array_mixed[mask_nan])

NaN element:
[nan nan nan]


Only complex

In [66]:
# Mask for complex
mask_complex = np.vectorize(lambda x: isinstance(x, complex))(array_mixed)
print("Complex element:")
print(array_mixed[mask_complex])

Complex element:
[(2+3j) (7+1j) (8+0j)]


# Array manipulation

## Change shape

### Reshape

In [68]:
a = np.arange(8)
print('Original Array:')
print(a)

b = a.reshape(4,2)
print('Modified array:')
print(b)


Original Array:
[0 1 2 3 4 5 6 7]
Modified array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


### Flatten

The flatten() method is used to convert a multidimensional array to a single-dimensional one, and the order argument specifies the order in which the array elements are read during flattening:

| `order` | Style | Read by | Result |
| ------- | ------------- | ---------------- | --------------------- |
| `'C'` | C-style | Row to column | \[0 1 2 3 4 5 6 7] |
| `'F'` | Fortran-style | Column to row | \[0 4 1 5 2 6 3 7] |
| `'A'` | Adaptive | Follows input | Can be `'C'` or `'F'` |
| `'K'` | Memory Order | Memory order | Can be different |

In [69]:
a = np.arange(8).reshape(2,4) # take copy

print('Original Array:')
print(a)


print('Array that has been flattened:')
print(a.flatten())

print('Flattented Array in F-Style Ordering:')
print(a.flatten(order = 'F'))
print('Flattened Array in A-Style Ordering:')
print(a.flatten(order = 'A'))
print('Flattented Array in K-Style Ordering:')
print(a.flatten(order = 'K'))
print('Flattented Array in C-Style Ordering:')
print(a.flatten(order = 'C'))

Original Array:
[[0 1 2 3]
 [4 5 6 7]]
Array that has been flattened:
[0 1 2 3 4 5 6 7]
Flattented Array in F-Style Ordering:
[0 4 1 5 2 6 3 7]
Flattened Array in A-Style Ordering:
[0 1 2 3 4 5 6 7]
Flattented Array in K-Style Ordering:
[0 1 2 3 4 5 6 7]
Flattented Array in C-Style Ordering:
[0 1 2 3 4 5 6 7]


### Ravel

The ravel() function returns a 1-dimensional (flat) array with a view of the original array (without creating a new copy unnecessarily).

In [70]:
a = np.arange(8).reshape(2,4) # Only view

print('Original Array:')
print(a)

print('Results of the Ravel Function:')
print(a.ravel())

print('Using Ravel Function in F-Style Ordering:')
print(a.ravel(order = 'F'))

Original Array:
[[0 1 2 3]
 [4 5 6 7]]
Results of the Ravel Function:
[0 1 2 3 4 5 6 7]
Using Ravel Function in F-Style Ordering:
[0 4 1 5 2 6 3 7]


| Aspects | `ravel()` | `flatten()` |
| --------- | ----------------------------------------------------- | ---------------------------------------- |
| Output | View if possible | Always copy |
| Memory | More economical | Safer (not tied to the original array) |
| Changes | If the original array changes, the result of `ravel()` changes as well | Unaffected |
| Performance | Faster | Slightly slower |

## Transpose operation

In [71]:
a = np.arange(12).reshape(3,4)

print('Original Array:')
print(a)

print('Array that has been transposed:')
print(np.transpose(a)) # parameters with an int list, according to dimensions. By default, the dimensions are reversed

print('Array that has been transposed with .T:')
print(a.T)

Original Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array that has been transposed:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Array that has been transposed with .T:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Merger of array

### Concatenate
* Purpose: Combining arrays along the existing axis (Axis 0, Axis 1, etc.).
* Requirements: The array dimension must be suitable in all axis except to be combined.
* Suitable for combining data with the same shape horizontally or vertically, for example adding new lines.

In [72]:
a = np.array([[1,2],[3,4]])

print('First Array:')
print(a)
b = np.array([[5,6],[7,8]])

print('Second Array:')
print(b)

print('a combination of two arrays on the axis 0:')
print(np.concatenate((a,b)) )

print('A combination of two arrays on the axis 1:')
print(np.concatenate((a,b),axis = 1))

First Array:
[[1 2]
 [3 4]]
Second Array:
[[5 6]
 [7 8]]
a combination of two arrays on the axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
A combination of two arrays on the axis 1:
[[1 2 5 6]
 [3 4 7 8]]


### stack
* Objective: Combine the array by adding a new axis.
* Requirements: All arrays must be exactly the same size.
* Used if you want to add new dimensions, such as combining images in format (amount, height, width).

In [73]:
a = np.array([[1,2],[3,4]])

print('First Array:')
print(a)
b = np.array([[5,6],[7,8]])

print('Second Array:')
print(b)

print('Stack two array on the axis 0:')
print(np.stack((a,b),0) )

print('Stack two arrays on the axis 1:')
print(np.stack((a,b),1))

First Array:
[[1 2]
 [3 4]]
Second Array:
[[5 6]
 [7 8]]
Stack two array on the axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Stack two arrays on the axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### hstack
* Objective: combining horizontal array (column).
* Requirements: The number of lines must be the same (for 2D array).
* Facilitate the combination of additional columns, suitable for compiling additional features in machine learning.

In [74]:
a = np.array([[1,2],[3,4]])

print('First Array:')
print(a)
b = np.array([[5,6],[7,8]])

print('Second Array:')
print(b)

print('Horizontal Stacking:')
c = np.hstack((a,b))
print(c)


First Array:
[[1 2]
 [3 4]]
Second Array:
[[5 6]
 [7 8]]
Horizontal Stacking:
[[1 2 5 6]
 [3 4 7 8]]


### vstack
* Objective: combining array vertically (row).
* Requirements: The number of columns must be the same (for 2D array).
* Suitable for adding data to the batch, for example combining training and testing data.

In [75]:
a = np.array([[1,2],[3,4]])

print('First Array:')
print(a)
b = np.array([[5,6],[7,8]])

print('Second Array:')
print(b)

print('Vertical Stacking:')
c = np.vstack((a,b))
print(c)


First Array:
[[1 2]
 [3 4]]
Second Array:
[[5 6]
 [7 8]]
Vertical Stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


| Function | Add a New Axis? | Join Direction | Size Requirements | When to Use? |
| ------------- | ------------------- | ----------------- | -------------------------- | ----------------------------------- |
| `concatenate` | ❌ No | Depends on `axis` | Same in all but axis | Regular concatenation (rows/columns) |
| `stack` | ✅ Yes | New Axis | All arrays exactly the same | Concatenate arrays in a new dimension |
| `hstack` | ❌ No | Horizontal | Same number of rows | Add new columns or features |
| `vstack` | ❌ No | Vertical | Same number of columns | Add new rows/data |

## Splitting Array (Separation of Array) to Sub-Array

### split

In [76]:
a = np.arange(9)

print('First Array:')
print(a)

print('Split array becomes 3 equivalent sub-array:')
b = np.split(a,3)
print(b)

print('split based on index on 1 -dimensional array:')
b = np.split(a,[4,5]) # numpy.split (ary, indices_or_sections, axis)
# The indicec_or_section parameter can be an integer,
# which shows the number of subarray the same size that will be made from input array.
print(b)


First Array:
[0 1 2 3 4 5 6 7 8]
Split array becomes 3 equivalent sub-array:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
split based on index on 1 -dimensional array:
[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]


### hsplit

In [77]:
a = np.arange(16).reshape(4,4)

print('First Array:')
print(a)

print('Horizontal splitting:')
b = np.hsplit(a,2)
print(b)


First Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


### vsplit

In [78]:
a = np.arange(16).reshape(4,4)

print('Early Array:')
print(a)

print('Vertical splitting:')
b = np.vsplit(a,2)
print(b)


Early Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Vertical splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## Changing the Array Element (Add/Remove)

### Resize

In [79]:
a = np.array([[1,2,3],
              [4,5,6]])

print('Early Array:')
print(a)

print('First Array Shape:')
print(a.shape)

b = np.resize(a, (3,2))

print('First Resize Array:')
print(b)

print('Second Array Shape:')
print(b.shape)

print('Second Array Resize:')
b = np.resize(a,(3,3))
print(b)


Early Array:
[[1 2 3]
 [4 5 6]]
First Array Shape:
(2, 3)
First Resize Array:
[[1 2]
 [3 4]
 [5 6]]
Second Array Shape:
(3, 2)
Second Array Resize:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


### Append

In [80]:
print('Initial array')
print(a)

print('Append element to array:')
print(np.append(a, [7,8,9]))

print('Append element along the axis 0:')
print(np.append(a, [[7,8,9]],axis = 0))

print('Append elements along the axis 1:')
print(np.append(a, [[5,5,5],[7,8,9]],axis = 1))


Initial array
[[1 2 3]
 [4 5 6]]
Append element to array:
[1 2 3 4 5 6 7 8 9]
Append element along the axis 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Append elements along the axis 1:
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


### Insert

In [81]:
a = np.array([[1,2],
              [3,4],
              [5,6]])

print('First Array:')
print(a)

print('Without Axis parameters. before the insertion array is flattened.')
print(np.insert(a,3,[11,12]))
print('Using Axis parameters. Value array in broadcast to equalize input.')

print('Broadcast along Axis 0:')
print(np.insert(a,1,[11],axis = 0))

print('Broadcast Sepanjanhg Axis 1:')
print(np.insert(a,1,11,axis = 1))


First Array:
[[1 2]
 [3 4]
 [5 6]]
Without Axis parameters. before the insertion array is flattened.
[ 1  2  3 11 12  4  5  6]
Using Axis parameters. Value array in broadcast to equalize input.
Broadcast along Axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
Broadcast Sepanjanhg Axis 1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


### delete

In [82]:
a = np.arange(12).reshape(3,4)

print('First Array:')
print(a)

print('Without Axis parameters, it is flattened before it is deleted:')
print(np.delete(a,5))

print('Column 2 is deleted:')
print(np.delete(a,1,axis = 1))

print('Row 2 Deleted:')
print(np.delete(a,1,axis = 0))

First Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Without Axis parameters, it is flattened before it is deleted:
[ 0  1  2  3  4  6  7  8  9 10 11]
Column 2 is deleted:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
Row 2 Deleted:
[[ 0  1  2  3]
 [ 8  9 10 11]]


### Unique Element

In [83]:
a = np.array([5,2,6,2,7,5,6,8,2,9])

print('First Array:')
print(a)

print('Unique Value from the First Array:')
z = np.unique(a)
print(z)

print('Array Index:')
z,indices = np.unique(a, return_index = True)
p = np.unique(a, return_index = True)
print(indices)
print(p[1])


First Array:
[5 2 6 2 7 5 6 8 2 9]
Unique Value from the First Array:
[2 5 6 7 8 9]
Array Index:
[1 0 2 4 7 9]
[1 0 2 4 7 9]


# Broadcasting Array
* Broadcasting means adjusting the shape of a small array to be able to operate with a large array.
* Numpy "spread" (broadcast) smaller array along the required dimensions.
* Two arrays can be broken if:
  1. They have the same number of dimensions, or one can be expanded.
  2. The size of each dimension is suitable, or one of them is worth 1.

#### Example 1

In [84]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)

[ 10  40  90 160]


#### Example 2

In [85]:
a = np.array([[0.0,0.0,0.0],
              [10.0,10.0,10.0],
              [20.0,20.0,20.0],
              [30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print('First Array:')
print(a)

print('Second Array:')
print(b)

print('First array + second array')
print(a + b)
print('First Array X Second Array')
print(a * b)


First Array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
Second Array:
[1. 2. 3.]
First array + second array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
First Array X Second Array
[[ 0.  0.  0.]
 [10. 20. 30.]
 [20. 40. 60.]
 [30. 60. 90.]]


### Case Study
1. Create two arrays with shape=(3,4) and shape(1,4)
2. Perform multiplication and subtraction operations

In [86]:
# Array A: Shape (3, 4)
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Array B: Shape (1, 4)
b = np.array([[2, 2, 2, 2]])

print("Array A:")
print(a)
print("Array B:")
print(b)

Array A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array B:
[[2 2 2 2]]


In [87]:
# Broadcasting multiplication
hasil_kali = a * b
print("Multiplication results a * b:")
print(hasil_kali)

Multiplication results a * b:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [88]:
# Broadcasting reduction
hasil_kurang = a - b
print("Reduction Results A - B:")
print(hasil_kurang)

Reduction Results A - B:
[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]


# Array iteration

#### Example 1

In [89]:
a = np.arange(0,60,5).reshape(3,4)
print('Original Array:')
print(a)

print('Modified array:')
for x in np.nditer(a):
   print(x, end=' ')


Original Array:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Modified array:
0 5 10 15 20 25 30 35 40 45 50 55 

* Iteration sequence is chosen to match the layout of the array memory, without considering a certain order.
* This can be seen by repeating the transpos from the array above.

#### Example 2

In [90]:
a = np.arange(0,60,5).reshape(3,4)

print('Original Array:')
print(a)

print('Transpose Array:')
b = a.T
print(b)

print('Modified array:')
for x in np.nditer(b):
   print(x, end=' ')

Original Array:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Transpose Array:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
Modified array:
0 5 10 15 20 25 30 35 40 45 50 55 

#### Iteration order
#### Example 3

In [91]:
a = np.arange(0,60,5).reshape(3,4)

print('Original Array:')
print(a)

print('Original Array Transpose:')
b = a.T
print(b)

print('Sort in C-Style Order:')
c = a.copy(order = 'C')
print(c)
for x in np.nditer(c):
   print(x, end=' ')

print('Sort in F-Style Order:')
c = a.copy(order = 'F')
print(c)
for x in np.nditer(c):
   print(x, end=' ')

Original Array:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Original Array Transpose:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
Sort in C-Style Order:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 5 10 15 20 25 30 35 40 45 50 55 Sort in F-Style Order:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 20 40 5 25 45 10 30 50 15 35 55 

#### Example 4

In [92]:
a = np.arange(0,60,5).reshape(3,4)

print('Original Array:')
print(a)

print('Sorted in C-Style Order:')
for x in np.nditer(a, order = 'C'):
   print(x, end=' ')

print('Sorted in In F-Style Order:')
for x in np.nditer(a, order = 'F'):
   print(x, end=' ')

Original Array:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Sorted in C-Style Order:
0 5 10 15 20 25 30 35 40 45 50 55 Sorted in In F-Style Order:
0 20 40 5 25 45 10 30 50 15 35 55 

### Modification of Array Element Value

In [93]:
a = np.arange(0,60,5).reshape(3,4)
print('Original Array:')
print(a)

for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x
   print(x, end=' ')
print('Array that has been modified:')
print(a)


Original Array:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 10 20 30 40 50 60 70 80 90 100 110 Array that has been modified:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


### external loop

In [94]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Original Array:')
print(a)

print('Modified array:')
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):
   print(x, end=' ')
print('Modification new')
for x in np.nditer(a, flags = ['external_loop'], order = 'C'):
   print(x, end=' ')


Original Array:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Modified array:
[ 0 20 40] [ 5 25 45] [10 30 50] [15 35 55] Modification new
[ 0  5 10 15 20 25 30 35 40 45 50 55] 

### Array iteration broadcasting

In [97]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('First Array:')
print(a)

print('Second Array:')
b = np.array([1, 2, 3, 4], dtype = int)
print(b)

print('Modified array:')
for x,y in np.nditer([a,b]):
   print("%d: %d " %(x, y), end = '')

First Array:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Second Array:
[1 2 3 4]
Modified array:
0: 1 5: 2 10: 3 15: 4 20: 1 25: 2 30: 3 35: 4 40: 1 45: 2 50: 3 55: 4 

# Numpy for Mathematics

## Trigonomeri function
Numpy has a standard trigonometric function that restores the trigonometric ratio for a certain angle in radians.

In [98]:
a = np.array([0,30,45,60,90])

print('Sine values of different angles:')
# Convert radians by multiplying by pi/180
print(np.sin(a*np.pi/180))

print('Cosine values of angles in array:')
print(np.cos(a*np.pi/180))

print('Tangent values of angles in array:')
print(np.tan(a*np.pi/180))

Sine values of different angles:
[0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values of angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent values of angles in array:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [99]:
a = np.array([0,30,45,60,90])

print('Array with sine values:')
sin = np.sin(a*np.pi/180)
print(sin)

print('Calculate the inverse sine of the angle. The return value is in radians.')
inv = np.arcsin(sin)
print(inv)

print('Check the result by converting to degrees:')
print(np.degrees(inv))

Array with sine values:
[0.         0.5        0.70710678 0.8660254  1.        ]
Calculate the inverse sine of the angle. The return value is in radians.
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
Check the result by converting to degrees:
[ 0. 30. 45. 60. 90.]


In [100]:
print('Arccos and Arctan functions behave similarly:')
cos = np.cos(a*np.pi/180)
print(cos)

print('Inverse from cos:')
inv = np.arccos(cos)
print(inv)

print('in degrees:')
print(np.degrees(inv))

Arccos and Arctan functions behave similarly:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Inverse from cos:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
in degrees:
[ 0. 30. 45. 60. 90.]


In [101]:
print('Tan function:')
tan = np.tan(a*np.pi/180)
print(tan)

print('Inverse from tan:')
inv = np.arctan(tan)
print(inv)

print('in degrees:')
print(np.degrees(inv))

Tan function:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
Inverse from tan:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
in degrees:
[ 0. 30. 45. 60. 90.]


## Rounding Function with numpy.round
__numpy.around(a,decimals)__

In [102]:
a = np.array([1.0,5.55, 123, 0.567, 25.532])

print('Original Array:')
print(a)

print('After rounding:')
print(np.around(a))
print(np.around(a, decimals = 1))


Original Array:
[  1.      5.55  123.      0.567  25.532]
After rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]


__np.floor__

This function returns the largest integer not greater than the input parameter. The base of the scalar x is the largest integer i, so i <= x. Note that in Python, floor always rounds away from 0.

In [103]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10,12.9])

print('Original Array:')
print(a)

print('Flooring Array:')
print(np.floor(a))


Original Array:
[-1.7  1.5 -0.2  0.6 10.  12.9]
Flooring Array:
[-2.  1. -1.  0. 10. 12.]


__np.ceil__

The ceil() function returns the ceiling of the input value, i.e., the scalar ceil x is the smallest integer i such that i >= x.

In [104]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10,12.9])

print('Original Array:')
print(a)

print('Ceiling Array:')
print(np.ceil(a))

Original Array:
[-1.7  1.5 -0.2  0.6 10.  12.9]
Ceiling Array:
[-1.  2. -0.  1. 10. 13.]


## Arithmetic operation

Inside the numpy there is a function to carry out, subtraction, multiplication and division

In [105]:
a = np.arange(9, dtype = np.float64).reshape(3,3)

print('First array:')
print(a)

print('Second array:')
b = np.array([10,10,10])
print(b)

print('Sum of 2 arrays:')
print(np.add(a,b))

print('Subtraction of 2 arrays:')
print(np.subtract(a,b))

print('Multiplication of 2 arrays:')
print(np.multiply(a,b))

print('Dividing 2 arrays:')
print(np.divide(a,b))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Second array:
[10 10 10]
Sum of 2 arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
Subtraction of 2 arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
Multiplication of 2 arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
Dividing 2 arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


### Power multiplication operation with numpy.power

In [106]:
a = np.array([10,100,1000])

print('Original array:')
print(a)

print('Using power function:')
print(np.power(a,2))

print('Second array:')
b = np.array([1,2,3])
print(b)

print('Using power function again:')
print(np.power(a,b))

Original array:
[  10  100 1000]
Using power function:
[    100   10000 1000000]
Second array:
[1 2 3]
Using power function again:
[        10      10000 1000000000]


Take the residual value of the share with np.mod/np.remainder

In [107]:
a = np.array([10,20,30])
b = np.array([3,5,7])

print('First array:')
print(a)

print('Second array:')
print(b)

print('using mod() function:')
print(np.mod(a,b))

print('using remainder() function:')
print(np.remainder(a,b))

First array:
[10 20 30]
Second array:
[3 5 7]
using mod() function:
[1 0 2]
using remainder() function:
[1 0 2]


# Statistical function

## Looking for the minimum and maximum value in an array

In [108]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])

print('Original array:')
print(a)

print('Using the amin(1) function:')
print(np.amin(a,axis=1))

print('Using the amin(0) function again:')
print(np.amin(a,0))

print('Using the amax() function:')
print(np.amax(a))

print('Using the amin() function:')
print(np.amin(a))

print('Using the amax() function again:')
print(np.amax(a,axis = 0))

print('Using the amax() function again:')
print(np.amax(a,axis = 1))

Original array:
[[3 7 5]
 [8 4 3]
 [2 4 9]]
Using the amin(1) function:
[3 3 2]
Using the amin(0) function again:
[2 4 3]
Using the amax() function:
9
Using the amin() function:
2
Using the amax() function again:
[8 7 9]
Using the amax() function again:
[7 8 9]


## Percentile

__np.percentile__

* A percentile (or one percentile) is a measure used in statistics that indicates the values below a certain percentage of observations in a group of observations.

__numpy.percentile(a, q, axis)__
a : Input array
q : The percentile to be calculated must be between 0-100
axis : axis

The percentile for a value in a given data set can be calculated using the formula:

n = (P/100) x N

where N = the number of values in the data set, P = the percentile, and n = the ordinal rank of the given value (with the values in the data set ordered from smallest to largest). For example, consider a class of 20 students who scored the following on their most recent test: 75, 77, 78, 78, 80, 81, 81, 82, 83, 84, 84, 84, 85, 87, 87, 88, 88, 88, 89, 90. These scores can be represented as a data set with 20 values: {75, 77, 78, 78, 80, 81, 81, 82, 83, 84, 84, 84, 85, 87, 87, 88, 88, 88, 89, 90}.

We can find the score that marks the 20th percentile by plugging the known values into the formula and solving for n:

n = (20/100) x 20

n = 4

The fourth value in the data set is a score of 78. This means that 78 marks the 20th percentile; of the students in the class, 20 percent scored 78 or lower.

In [109]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])

print('Original array:')
print(a)

print('Using the percentile() function:')
print(np.percentile(a,50))

print('Using the percentile() function on axis 1:')
print(np.percentile(a,50, axis = 1))

print('Using the percentile() function on axis 0:')
print(np.percentile(a,50, axis = 0))

Original array:
[[30 40 70]
 [80 20 10]
 [50 90 60]]
Using the percentile() function:
50.0
Using the percentile() function on axis 1:
[40. 20. 60.]
Using the percentile() function on axis 0:
[50. 40. 60.]


## Median
The median is defined as the value that separates the higher half of a data sample from the lower half, and can be calculated using __numpy.median__

In [110]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]])

print('Original array:')
print(a)

print('Using the median() function:')
print(np.median(a))

print('Using the median() function along the 0-axis:')
print(np.median(a, axis = 0))

print('Using the median() function along the 1-axis:')
print(np.median(a, axis = 1))

Original array:
[[30 65 70]
 [80 95 10]
 [50 90 60]]
Using the median() function:
65.0
Using the median() function along the 0-axis:
[50. 90. 60.]
Using the median() function along the 1-axis:
[65. 80. 60.]


## Mean
* The mean is the sum of the elements along an axis divided by the number of elements.
* The __numpy.mean()__ function returns the arithmetic mean of the elements in an array.
* If an axis is explicitly specified, it is calculated based on its values.

In [111]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

print('Original array:')
print(a)

print('Using the mean() function:')
print(np.mean(a))

print('Using the mean() function along the 0-axis:')
print(np.mean(a, axis = 0))

print('Using the mean() function along the 1-axis:')
print(np.mean(a, axis = 1))

Original array:
[[1 2 3]
 [3 4 5]
 [4 5 6]]
Using the mean() function:
3.6666666666666665
Using the mean() function along the 0-axis:
[2.66666667 3.66666667 4.66666667]
Using the mean() function along the 1-axis:
[2. 4. 5.]


## Weighted Average
* A weighted average is the average resulting from multiplying each element by a factor that reflects its importance.
* The __numpy.average()__ function calculates the weighted average of the elements in an array according to their respective weights assigned to them in another array.
* The function can have an axis parameter.
* If an axis is not specified, the array is flattened.
* Given the array [1,2,3,4] and the corresponding weights [4,3,2,1], the weighted average is calculated by adding the products of the corresponding elements and dividing the sum by the sum of the weights.
* Weighted average = (1*4+2*3+3*2+4*1)/(4+3+2+1)

In [112]:
a = np.array([1,2,3,4])

print('Original array:')
print(a)

print('Using the average() function:')
print(np.average(a))

print('Using the mean() function:')
print(np.mean(a))

# This is the same as the mean when weights are not defined
wts = np.array([4,3,2,1])

print('Using the average() function again:')
print(np.average(a,weights = wts))

# Returns the weighted sum, if the return parameter is set to True
print('Weighted sum')
print(np.average([1,2,3, 4],weights = [4,3,2,1], returned = True))

Original array:
[1 2 3 4]
Using the average() function:
2.5
Using the mean() function:
2.5
Using the average() function again:
2.0
Weighted sum
(np.float64(2.0), np.float64(10.0))


## Standard deviation
* Standard Deviation is a measure of how scattered data in relation to mean.
* Low Deviation Standard means data grouping around average, and high deviation standards indicate more spread data.

In [113]:
np.std([1,2,3,4])

np.float64(1.118033988749895)

## Variance
* Variance is a measure of variability.
* This is calculated by taking the average quadratic deviation from the mean.
* Variance tells you the level of distribution in your data collection.
* The more data spread, the greater the variance in relation to the mean

In [114]:
print(np.var([1,2,3,4]))

1.25


Standard deviation measures how far the numbers are in a data collection. Variance, on the other hand, gives the actual value of how many numbers in the data collection vary from average

# Thank you