# Introduction to NumPy

In [1]:
import numpy as np
import pandas as pd

__numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)__

- object : Objek apa pun yang mengekspos metode antarmuka array mengembalikan array, atau apa pun (bersarang) urutan
- dtype  : type data, opsional
- copy   : Opsional. Secara default (True), objek disalin
- order  : C (baris mayor) atau F (utama kolom) atau A (apa saja) (default)
- subok  : Secara default, array yang dikembalikan dipaksa menjadi array kelas dasar. Jika benar, sub-kelas akan diberikan
- ndimin : Menentukan dimensi minimum dari array yang dihasilkan

#### Contoh 1
Masukkan nilai integer atau nilai dengan tipe data apapun sesuai kebutuhan

In [2]:
arr = np.array([1,2,3])

In [3]:
print(arr)

[1 2 3]


In [4]:
arr[2]

np.int64(3)

#### Contoh 2 
array 2 dimensi

In [5]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


# Tipe Data Array

#### contoh 1 
array dengan tipe data integer

In [6]:
print(a.dtype)
print(arr.dtype)

int64
int64


#### contoh 2 
tipe data dengan unicode string

In [7]:
arr_1 = np.array(['rambutan', 'apel', 'jeruk'])
print(arr_1.dtype)

<U8


In [8]:
arr_1 = np.array(['r', 'a', 'j'])
print(arr_1.dtype)

<U1


#### contoh 3 
tipe data yang didefinisikan

In [9]:
arr_2 = np.array([1, 2, 3, 4], dtype='S')

In [10]:
print(arr_2)

[b'1' b'2' b'3' b'4']


In [11]:
print(arr_2.dtype)

|S1


#### contoh 4 
tipe data yang diubah

In [12]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

In [13]:
print(newarr)

[1 2 3]


In [14]:
print(newarr.dtype)

int32


In [15]:
print(arr.dtype)

float64


Membuat array dari data yang sudah ada\
konversi list menjadi ndarray

In [16]:
x = [1, 2, 3, 4, 5]
print(type(x))
p = np.asarray(x)
print(p.dtype)
print(x)
print(p)

<class 'list'>
int64
[1, 2, 3, 4, 5]
[1 2 3 4 5]


#### contoh 2
konversi list menjadi array dengan tipe data yang didefinisikan

In [17]:
x = [1, 2, 3, 4, 5]
print(type(x))

<class 'list'>


In [18]:
x = np.asarray(x, dtype='f')
print(x.dtype)
print(x)

float32
[1. 2. 3. 4. 5.]


### Task 1:
- Buat dua variable tuple yang berisi angka
- masukkan dua variable tuple tersebut kedalam variable bertipe data list
- konversi list tersebut menjadi array numpy

In [19]:
# Jawab
angka_tuple = ((919, 2019), (2839, 333))
print(type(angka_tuple))

<class 'tuple'>


In [20]:
angka_numpy = np.array(angka_tuple)
print(angka_numpy.dtype)

int64


In [21]:
print(type(angka_numpy))

<class 'numpy.ndarray'>


* Membuat rentang nilai menggunakan numpy:\
* membuat dataframe menggunakan rentang nilai random dan deterministik\
__numpy.arange(start, stop, step, dtype)__

In [22]:
z = np.arange(0, 1, 0.1, dtype='f')
x = np.arange(1,11, 1)
y = np.arange(10,20, 1)

In [23]:
print(z)
print(x)
print(y)
print("-"*100)

[0.         0.1        0.2        0.3        0.4        0.5
 0.6        0.7        0.8        0.90000004]
[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14 15 16 17 18 19]
----------------------------------------------------------------------------------------------------


In [24]:
pd.DataFrame({'z' : z, 'x' : x, 'y' : y})

z   x   y
0  0.0   1  10
1  0.1   2  11
2  0.2   3  12
3  0.3   4  13
4  0.4   5  14
5  0.5   6  15
6  0.6   7  16
7  0.7   8  17
8  0.8   9  18
9  0.9  10  19

### Operasi umum lain di NumPy

membuat array dengan nilai 1 di numpy

In [25]:
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


membuat array dengan nilai 0 di numpy

In [26]:
x = np.zeros((2,2))
print(x)

[[0. 0.]
 [0. 0.]]


In [27]:
x = np.full((3,4), 0.72)
print(x)

[[0.72 0.72 0.72 0.72]
 [0.72 0.72 0.72 0.72]
 [0.72 0.72 0.72 0.72]]


In [28]:
x = np.random.rand(5,4)
print(x)

[[0.42151903 0.45497842 0.99006168 0.2978577 ]
 [0.6340651  0.2464419  0.11743011 0.78360822]
 [0.67239623 0.62080163 0.75282053 0.29379257]
 [0.90205635 0.80205912 0.92639265 0.97601444]
 [0.14071526 0.71212609 0.12131724 0.7484756 ]]


In [29]:
pd.DataFrame(x, columns=['x', 'y', 'z','w'])

x         y         z         w
0  0.421519  0.454978  0.990062  0.297858
1  0.634065  0.246442  0.117430  0.783608
2  0.672396  0.620802  0.752821  0.293793
3  0.902056  0.802059  0.926393  0.976014
4  0.140715  0.712126  0.121317  0.748476

### Tugas Lagi
* Tugas 1 : Generate random array menggunakan np.random.rand dengan jumlah baris 3 serta jumlah kolom 4 dan masukkan ke dalam dataframe
* Tugas 2 : Generate array dengan nilai satu dan nol yang memiliki baris 5 dan 6 kolom di dua variable berbeda kemudian konversi ke dataframe dan concat keduanya

In [30]:
# Tugas 1
acak_numpy = np.random.rand(3,4)
print(acak_numpy)

[[0.87366974 0.32995358 0.19352098 0.61170908]
 [0.52171057 0.9677869  0.12005079 0.57002793]
 [0.20182541 0.21115255 0.58736136 0.39945217]]


In [31]:
pd.DataFrame(acak_numpy,columns=["A","B","C","D"])

A         B         C         D
0  0.873670  0.329954  0.193521  0.611709
1  0.521711  0.967787  0.120051  0.570028
2  0.201825  0.211153  0.587361  0.399452

In [32]:
# Tugas 2
array_ones = np.ones((5, 6), dtype=int)   # array 5x6 dengan semua nilai 1
array_zeros = np.zeros((5, 6), dtype=int) # array 5x6 dengan semua nilai 0

Konversi ke dataframe

In [33]:
df_ones = pd.DataFrame(array_ones, columns=[f"C{i+1}" for i in range(6)])
df_zeros = pd.DataFrame(array_zeros, columns=[f"C{i+1}" for i in range(6)])

Gabungkan secara vertikal (baris) → axis=0

In [34]:
df_concat = pd.concat([df_ones, df_zeros], axis=0, ignore_index=True)

In [35]:
df_concat

C1  C2  C3  C4  C5  C6
0   1   1   1   1   1   1
1   1   1   1   1   1   1
2   1   1   1   1   1   1
3   1   1   1   1   1   1
4   1   1   1   1   1   1
5   0   0   0   0   0   0
6   0   0   0   0   0   0
7   0   0   0   0   0   0
8   0   0   0   0   0   0
9   0   0   0   0   0   0

# Slicing and Indexing

## Field Access dan Basic Indexing

#### contoh 1 
index tunggal, field index

In [36]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
b = a[5]
print(b)

5


#### Contoh 2

In [38]:
# Contoh 2
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
s = slice(2,7,2)
print(a[s])

[2 4 6]


In [40]:
print(a[slice(1,8,3)])

[1 4 7]


#### Contoh 3

In [41]:
a = np.arange(10)
b = a[2:7:2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


#### contoh 4 
slicing index hanya dengan menggunakan parameter start

In [42]:
a = np.arange(10)
print(a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


#### contoh 5 
slicing menggunakan start dan stop index

In [43]:
a = np.arange(10)
print(a)
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


#### contoh 6 
slicing pada array dua dimensi

In [44]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

# slice item dimulai dari suatu indeks
print('slice array dari index a[1:]')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
slice array dari index a[1:]
[[3 4 5]
 [4 5 6]]


#### contoh 7 
menggunakan __ellipsis (...)__

In [45]:
a = np.array([[1,2,3],
              [3,4,5],
              [4,5,6]])

print('Array kita:')
print(a)
print('\n')

# ini mengembalikan item di kolom kedua dari array utama
print('item dari kolom kedua:')
print(a[...,1])
print('\n')

# slice semua item dari baris kedua
print('Item dari baris kedua:')
print(a[1,...])
print('\n')

# kita akan slice item dari kolom 1 dan seterusnya
print('item dari kolom 1 dan seterusnya:')
print(a[...,1:])


Array kita:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


item dari kolom kedua:
[2 4 5]


Item dari baris kedua:
[3 4 5]


item dari kolom 1 dan seterusnya:
[[2 3]
 [4 5]
 [5 6]]


### Studi Kasus
1. Buat array 2 dimensi dengan shape=(3,4)
2. Index dengan mengambil item dari baris kedua dan seterusnya sampai bariss terakhir
3. Index dengan mengambil item dari kolom 1 dan 2

In [46]:
array_2d = np.array([[10, 20, 30, 40],
                     [50, 60, 70, 80],
                     [90, 100, 110, 120]])

print("Array 2D (3x4):")
print(array_2d)

Array 2D (3x4):
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [47]:
baris2_akhir = array_2d[1:]  # Ambil baris ke-2 sampai akhir (index 1 sampai selesai)
print("\nBaris kedua sampai terakhir:")
print(baris2_akhir)


Baris kedua sampai terakhir:
[[ 50  60  70  80]
 [ 90 100 110 120]]


In [48]:
col_1_2 = array_2d[:, 0:2]  # Ambil semua baris, kolom ke-1 dan ke-2 (indeks 0 dan 1)
print("\nKolom 1 dan 2 dari seluruh baris:")
print(col_1_2)


Kolom 1 dan 2 dari seluruh baris:
[[ 10  20]
 [ 50  60]
 [ 90 100]]


## Advance Indexing

### Integer Indexing

#### contoh 1 
mengakses element dari array dua dimensi dengan menentukan baris dan kolom yang disalin

In [49]:
x = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [50]:
y = x[[0,1,2], [0,1,1]]
print(y)

[1 4 6]


#### contoh 2 
mengakses element dari array dua dimensi dengan menentukan baris dan kolom yang disalin

In [51]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])

print('array asli:')
print(x)
print("")
rows = np.array([[0,0],[3,3]]) #Baris pertama dan keempat
cols = np.array([[0,2],[0,2]]) #Kolom pertama dan ketiga
y = x[rows,cols]

print('Hasil dari indeks integer:')
print(y)

array asli:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Hasil dari indeks integer:
[[ 0  2]
 [ 9 11]]


#### contoh 3

In [52]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])

print('Array asli:')
print(x)
print('\n')

# slicing
z = x[1:4,1:3]

print('setelah, hasil array menjadi:')
print(z)
print('\n')

# using advanced index for column
y = x[1:4,[1,2]]

print('slicing dengan advance index untuk column:')
print(y)

Array asli:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


setelah, hasil array menjadi:
[[ 4  5]
 [ 7  8]
 [10 11]]


slicing dengan advance index untuk column:
[[ 4  5]
 [ 7  8]
 [10 11]]


## Boolean Indexing

#### contoh 1
mengambil elemen dengan index boolean (kondisi)

In [53]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])

print('Array asli:')
print(x)
print('\n')

# Akan dicetak elemen yang lebih dari 5
print('Elemen yang lebih besar dari 5:')
print(x[x > 5])

Array asli:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Elemen yang lebih besar dari 5:
[ 6  7  8  9 10 11]


#### contoh 2

In [54]:
a = np.array([np.nan, 1,2,np.nan,3,4,5])
print(a[np.isnan(a)])

[nan nan]


#### contoh 3

In [55]:
a = np.array([1, 2+6j, 5, 3.5+5j])
print(a[~np.iscomplex(a)])
print(a[np.iscomplex(a)])

[1.+0.j 5.+0.j]
[2. +6.j 3.5+5.j]


### Studi Kasus
1. Buat array 2 dimensi dengan shape=(3,4) yang
  isinya campuran antara complex, nan dan integer
2. Ambil elemen dengan menggunakan index boolean khusus integer, khusus nan dan khusus complex

In [57]:
# Membuat array campuran complex, NaN, dan integer
array_mixed = np.array([
    [1, 2+3j, np.nan, 4],
    [5, 6, 7+1j, np.nan],
    [8+0j, 9, 10, np.nan]
], dtype=object)

print("Array Campuran:")
print(array_mixed)

Array Campuran:
[[1 (2+3j) nan 4]
 [5 6 (7+1j) nan]
 [(8+0j) 9 10 nan]]


Selanjutnya akan diambil elemen dengan indeks boolean untuk masing-masing jenis

Hanya integer

In [58]:
# Buat mask untuk integer
mask_int = np.vectorize(lambda x: isinstance(x, int))(array_mixed)
print("Elemen Integer:")
print(array_mixed[mask_int])

Elemen Integer:
[1 4 5 6 9 10]


Hanya NaN

In [59]:
# Mask untuk NaN
mask_nan = np.vectorize(lambda x: isinstance(x, float) and np.isnan(x))(array_mixed)
print("Elemen NaN:")
print(array_mixed[mask_nan])

Elemen NaN:
[nan nan nan]


Hanya complex

In [60]:
# Mask untuk complex
mask_complex = np.vectorize(lambda x: isinstance(x, complex))(array_mixed)
print("\nElemen Complex:")
print(array_mixed[mask_complex])


Elemen Complex:
[(2+3j) (7+1j) (8+0j)]


# Array Manipulation

## Mengubah Shape

### reshape

In [61]:
a = np.arange(8)
print('Array asli:')
print(a)
print('\n')

b = a.reshape(4,2)
print('Array yang telah di modifikasi:')
print(b)


Array asli:
[0 1 2 3 4 5 6 7]


Array yang telah di modifikasi:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


### Flatten

Metode flatten() digunakan untuk mengubah array multidimensi menjadi satu dimensi, dan argumen order menentukan urutan pembacaan elemen array saat diflatten:

| `order` | Gaya          | Baca berdasarkan | Hasil                 |
| ------- | ------------- | ---------------- | --------------------- |
| `'C'`   | C-style       | Baris ke kolom   | \[0 1 2 3 4 5 6 7]    |
| `'F'`   | Fortran-style | Kolom ke baris   | \[0 4 1 5 2 6 3 7]    |
| `'A'`   | Adaptive      | Mengikuti input  | Bisa `'C'` atau `'F'` |
| `'K'`   | Memory Order  | Urutan memori    | Bisa berbeda          |


In [62]:
a = np.arange(8).reshape(2,4) #take copy

print('Array asli:')
print(a)


print('Array yang telah di flattened:')
print(a.flatten())

print('flattened array dalam F-style ordering:')
print(a.flatten(order = 'F'))
print('flattened array dalam A-style ordering:')
print(a.flatten(order = 'A'))
print('flattened array dalam K-style ordering:')
print(a.flatten(order = 'K'))
print('flattened array dalam C-style ordering:')
print(a.flatten(order = 'C'))

Array asli:
[[0 1 2 3]
 [4 5 6 7]]
Array yang telah di flattened:
[0 1 2 3 4 5 6 7]
flattened array dalam F-style ordering:
[0 4 1 5 2 6 3 7]
flattened array dalam A-style ordering:
[0 1 2 3 4 5 6 7]
flattened array dalam K-style ordering:
[0 1 2 3 4 5 6 7]
flattened array dalam C-style ordering:
[0 1 2 3 4 5 6 7]


### Ravel

Fungsi ravel() mengembalikan array 1 dimensi (datar) dengan view dari array asli (tidak membuat salinan baru jika tidak perlu).

In [63]:
a = np.arange(8).reshape(2,4) # only view

print('Array asli:')
print(a)

print('hasil dari fungsi ravel:')
print(a.ravel())

print('menggunakan ravel function dalam F-style ordering:')
print(a.ravel(order = 'F'))

Array asli:
[[0 1 2 3]
 [4 5 6 7]]
hasil dari fungsi ravel:
[0 1 2 3 4 5 6 7]
menggunakan ravel function dalam F-style ordering:
[0 4 1 5 2 6 3 7]


| Aspek     | `ravel()`                                             | `flatten()`                              |
| --------- | ----------------------------------------------------- | ---------------------------------------- |
| Output    | View jika memungkinkan                                | Selalu salinan (copy)                    |
| Memori    | Lebih hemat                                           | Lebih aman (tidak terikat ke array asli) |
| Perubahan | Jika array asli berubah, hasil `ravel()` ikut berubah | Tidak terpengaruh                        |
| Kinerja   | Lebih cepat                                           | Sedikit lebih lambat                     |


## Operasi Transpose

In [64]:
a = np.arange(12).reshape(3,4)

print('Array asli:')
print(a)

print('Array yang telah di transpose:')
print(np.transpose(a)) #parameter dengan list int, sesuai dengan dimensi. Secara default, dimensi dibalik

print('Array yang telah di transpos dengan .T:')
print(a.T)

Array asli:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array yang telah di transpose:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Array yang telah di transpos dengan .T:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Penggabungan array

### concatenate
* Tujuan: Menggabungkan array sepanjang sumbu yang sudah ada (axis 0, axis 1, dst).
* Syarat: Dimensi array harus cocok di semua axis kecuali yang akan digabung.
* Cocok untuk menggabungkan data yang bentuknya sama secara horizontal atau vertikal, misalnya menambahkan baris baru.

In [65]:
a = np.array([[1,2],[3,4]])

print('Array Pertama:')
print(a)
b = np.array([[5,6],[7,8]])

print('Array Kedua:')
print(b)

print('gabungan dua array di sumbu 0:')
print(np.concatenate((a,b)) )

print('gabungan dua array di sumbu 1:')
print(np.concatenate((a,b),axis = 1))

Array Pertama:
[[1 2]
 [3 4]]
Array Kedua:
[[5 6]
 [7 8]]
gabungan dua array di sumbu 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
gabungan dua array di sumbu 1:
[[1 2 5 6]
 [3 4 7 8]]


### stack
* Tujuan: Menggabungkan array dengan menambahkan sumbu baru.
* Syarat: Semua array harus berukuran sama persis.
* Digunakan jika kamu ingin menambahkan dimensi baru, seperti menggabungkan gambar dalam format (jumlah, tinggi, lebar).

In [66]:
a = np.array([[1,2],[3,4]])

print('Array Pertama:')
print(a)
b = np.array([[5,6],[7,8]])

print('Array kedua:')
print(b)

print('Stack dua array pada sumbu 0:')
print(np.stack((a,b),0) )

print('Stack dua array pada sumbu 1:')
print(np.stack((a,b),1))

Array Pertama:
[[1 2]
 [3 4]]
Array kedua:
[[5 6]
 [7 8]]
Stack dua array pada sumbu 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Stack dua array pada sumbu 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### hstack
* Tujuan: Menggabungkan array secara horizontal (kolom).
* Syarat: Jumlah baris harus sama (untuk array 2D).
* Mempermudah penggabungan kolom tambahan, cocok untuk menyusun fitur-fitur tambahan dalam machine learning.

In [67]:
a = np.array([[1,2],[3,4]])

print('Array Pertama:')
print(a)
b = np.array([[5,6],[7,8]])

print('Array Kedua:')
print(b)

print('Horizontal stacking:')
c = np.hstack((a,b))
print(c)


Array Pertama:
[[1 2]
 [3 4]]
Array Kedua:
[[5 6]
 [7 8]]
Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]


### vstack
* Tujuan: Menggabungkan array secara vertikal (baris).
* Syarat: Jumlah kolom harus sama (untuk array 2D).
* Cocok untuk menambahkan data ke dalam batch, misalnya menggabungkan data training dan testing.

In [68]:
a = np.array([[1,2],[3,4]])

print('Array pertama:')
print(a)
b = np.array([[5,6],[7,8]])

print('Array kedua:')
print(b)

print('Vertical stacking:')
c = np.vstack((a,b))
print(c)


Array pertama:
[[1 2]
 [3 4]]
Array kedua:
[[5 6]
 [7 8]]
Vertical stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


| Fungsi        | Menambah Axis Baru? | Arah Gabung       | Syarat Ukuran              | Kapan Digunakan?                    |
| ------------- | ------------------- | ----------------- | -------------------------- | ----------------------------------- |
| `concatenate` | ❌ Tidak             | Tergantung `axis` | Sama di semua kecuali axis | Penggabungan biasa (baris/kolom)    |
| `stack`       | ✅ Ya                | Sumbu Baru        | Semua array sama persis    | Menyatukan array dalam dimensi baru |
| `hstack`      | ❌ Tidak             | Horizontal        | Sama jumlah baris          | Tambah kolom atau fitur baru        |
| `vstack`      | ❌ Tidak             | Vertikal          | Sama jumlah kolom          | Tambah baris/data baru              |


## Splitting Array (Pemisahan Array) menjadi sub-array

### split

In [69]:
a = np.arange(9)

print('Array pertama:')
print(a)

print('split array menjadi 3 sub-array yang setara:')
b = np.split(a,3)
print(b)

print('split berdasarkan index pada array 1 dimensi:')
b = np.split(a,[4,5]) # numpy.split(ary, indices_or_sections, axis)
# parameter indicec_or_section dapat berupa bilangan bulat,
#yang menunjukkan jumlah subarray berukuran sama yang akan dibuat dari array input.
print(b)


Array pertama:
[0 1 2 3 4 5 6 7 8]
split array menjadi 3 sub-array yang setara:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
split berdasarkan index pada array 1 dimensi:
[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]


### hsplit

In [70]:
a = np.arange(16).reshape(4,4)

print('Array pertama:')
print(a)

print('Horizontal splitting:')
b = np.hsplit(a,2)
print(b)


Array pertama:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


### vsplit

In [71]:
a = np.arange(16).reshape(4,4)

print('Array awal:')
print(a)

print('Vertical splitting:')
b = np.vsplit(a,2)
print(b)


Array awal:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Vertical splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## Mengubah Element Array (Add/Remove)

### Resize

In [72]:
a = np.array([[1,2,3],
              [4,5,6]])

print('Array awal:')
print(a)

print('shape array pertama:')
print(a.shape)

b = np.resize(a, (3,2))

print('Array resize pertama:')
print(b)

print('shape array kedua:')
print(b.shape)

print('resize array kedua:')
b = np.resize(a,(3,3))
print(b)


Array awal:
[[1 2 3]
 [4 5 6]]
shape array pertama:
(2, 3)
Array resize pertama:
[[1 2]
 [3 4]
 [5 6]]
shape array kedua:
(3, 2)
resize array kedua:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


### Append

In [73]:
print('Array Awal')
print(a)

print('Append elemen ke array:')
print(np.append(a, [7,8,9]))

print('Append element sepanjang sumbu 0:')
print(np.append(a, [[7,8,9]],axis = 0))

print('Append elemen sepanjang sumbu 1:')
print(np.append(a, [[5,5,5],[7,8,9]],axis = 1))


Array Awal
[[1 2 3]
 [4 5 6]]
Append elemen ke array:
[1 2 3 4 5 6 7 8 9]
Append element sepanjang sumbu 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Append elemen sepanjang sumbu 1:
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


### Insert

In [74]:
a = np.array([[1,2],
              [3,4],
              [5,6]])

print('Array pertama:')
print(a)

print('tanpa parameter axis. sebelum insertion arraynya di flattened.')
print(np.insert(a,3,[11,12]))
print('Menggunakan parameter axis. value arraynya di broadcast untuk menyamakan input.')

print('Broadcast sepanjang axis 0:')
print(np.insert(a,1,[11],axis = 0))

print('Broadcast sepanjanhg axis 1:')
print(np.insert(a,1,11,axis = 1))


Array pertama:
[[1 2]
 [3 4]
 [5 6]]
tanpa parameter axis. sebelum insertion arraynya di flattened.
[ 1  2  3 11 12  4  5  6]
Menggunakan parameter axis. value arraynya di broadcast untuk menyamakan input.
Broadcast sepanjang axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
Broadcast sepanjanhg axis 1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


### delete

In [75]:
a = np.arange(12).reshape(3,4)

print('Array pertama:')
print(a)

print('tanpa parameter axis maka di flattened sebelum dihapus:')
print(np.delete(a,5))

print('kolom 2 dihapus:')
print(np.delete(a,1,axis = 1))

print('baris 2 dihapus:')
print(np.delete(a,1,axis = 0))

Array pertama:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
tanpa parameter axis maka di flattened sebelum dihapus:
[ 0  1  2  3  4  6  7  8  9 10 11]
kolom 2 dihapus:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
baris 2 dihapus:
[[ 0  1  2  3]
 [ 8  9 10 11]]


### Elemen unik

In [76]:
a = np.array([5,2,6,2,7,5,6,8,2,9])

print('Array pertama:')
print(a)

print('value unik dari array pertama:')
z = np.unique(a)
print(z)

print('index array:')
z,indices = np.unique(a, return_index = True)
p = np.unique(a, return_index = True)
print(indices)
print(p[1])


Array pertama:
[5 2 6 2 7 5 6 8 2 9]
value unik dari array pertama:
[2 5 6 7 8 9]
index array:
[1 0 2 4 7 9]
[1 0 2 4 7 9]


# Broadcasting array
* Broadcasting artinya menyesuaikan bentuk array kecil agar bisa beroperasi dengan array besar.
* NumPy "menyebarkan" (broadcast) array yang lebih kecil sepanjang dimensi yang diperlukan.
* Dua array bisa di-broadcast jika:
  1. Mereka memiliki jumlah dimensi yang sama, atau salah satu bisa di-expand.
  2. Ukuran setiap dimensi cocok, atau salah satunya bernilai 1.

#### Contoh 1

In [77]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)

[ 10  40  90 160]


#### Contoh 2

In [78]:
a = np.array([[0.0,0.0,0.0],
              [10.0,10.0,10.0],
              [20.0,20.0,20.0],
              [30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print('Array pertama:')
print(a)

print('Array kedua:')
print(b)

print('Array pertama + Array kedua')
print(a + b)
print('Array pertama x Array kedua')
print(a * b)


Array pertama:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
Array kedua:
[1. 2. 3.]
Array pertama + Array kedua
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
Array pertama x Array kedua
[[ 0.  0.  0.]
 [10. 20. 30.]
 [20. 40. 60.]
 [30. 60. 90.]]


### Studi Kasus
1. Buat dua array yang memiliki shape=(3,4) dan shape (1,4)
2. Lakukan operasi perkalian dan pengurangan

In [79]:
# Array A: shape (3, 4)
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Array B: shape (1, 4)
b = np.array([[2, 2, 2, 2]])

print("Array A:")
print(a)
print("Array B:")
print(b)

Array A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array B:
[[2 2 2 2]]


In [80]:
# Perkalian broadcasting
hasil_kali = a * b
print("Hasil Perkalian A * B:")
print(hasil_kali)

Hasil Perkalian A * B:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [81]:
# Pengurangan broadcasting
hasil_kurang = a - b
print("Hasil Pengurangan A - B:")
print(hasil_kurang)

Hasil Pengurangan A - B:
[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]


# Array Iteration

#### contoh 1

In [82]:
a = np.arange(0,60,5).reshape(3,4)
print('Array asli:')
print(a)

print('Array yang telah di modifikasi:')
for x in np.nditer(a):
   print(x, end=' ')


Array asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Array yang telah di modifikasi:
0 5 10 15 20 25 30 35 40 45 50 55 

* Urutan iterasi dipilih agar sesuai dengan tata letak memori array, tanpa mempertimbangkan urutan tertentu.
* Ini dapat dilihat dengan mengulangi transpos dari array di atas.

#### Contoh 2

In [83]:
a = np.arange(0,60,5).reshape(3,4)

print('Array asli:')
print(a)

print('Array yang di transpose:')
b = a.T
print(b)

print('Array yang telah di modifikasi:')
for x in np.nditer(b):
   print(x, end=' ')

Array asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Array yang di transpose:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
Array yang telah di modifikasi:
0 5 10 15 20 25 30 35 40 45 50 55 

#### Iteration Order
#### Contoh 3

In [84]:
a = np.arange(0,60,5).reshape(3,4)

print('Array asli:')
print(a)

print('Transpos array asli:')
b = a.T
print(b)

print('urutkan dalam C-style order:')
c = a.copy(order = 'C')
print(c)
for x in np.nditer(c):
   print(x, end=' ')

print('urutkan dalam F-style order:')
c = a.copy(order = 'F')
print(c)
for x in np.nditer(c):
   print(x, end=' ')

Array asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Transpos array asli:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
urutkan dalam C-style order:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 5 10 15 20 25 30 35 40 45 50 55 urutkan dalam F-style order:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 20 40 5 25 45 10 30 50 15 35 55 

#### Contoh 4

In [85]:
a = np.arange(0,60,5).reshape(3,4)

print('Array asli:')
print(a)

print('Diurutkan dalam C-style order:')
for x in np.nditer(a, order = 'C'):
   print(x, end=' ')

print('Diurutkan dalam in F-style order:')
for x in np.nditer(a, order = 'F'):
   print(x, end=' ')

Array asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Diurutkan dalam C-style order:
0 5 10 15 20 25 30 35 40 45 50 55 Diurutkan dalam in F-style order:
0 20 40 5 25 45 10 30 50 15 35 55 

### modifikasi nilai elemen array

In [86]:
a = np.arange(0,60,5).reshape(3,4)
print('Array asli:')
print(a)

for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x
   print(x, end=' ')
print('Array yang telah dimodifikasi:')
print(a)


Array asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 10 20 30 40 50 60 70 80 90 100 110 Array yang telah dimodifikasi:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


### eksternal loop

In [87]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Array asli:')
print(a)

print('Array yang telah di modifikasi:')
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):
   print(x, end=' ')
print('\nModifikasi baru')
for x in np.nditer(a, flags = ['external_loop'], order = 'C'):
   print(x, end=' ')


Array asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Array yang telah di modifikasi:
[ 0 20 40] [ 5 25 45] [10 30 50] [15 35 55] 
Modifikasi baru
[ 0  5 10 15 20 25 30 35 40 45 50 55] 

### broadcasting iterasi array

In [88]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Array pertama:')
print(a)

print('Array kedua:')
b = np.array([1, 2, 3, 4], dtype = int)
print(b)

print('Array yang telah di modifikasi:')
for x,y in np.nditer([a,b]):
   print("%d:%d" % (x,y), end=' ')

Array pertama:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Array kedua:
[1 2 3 4]
Array yang telah di modifikasi:
0:1 5:2 10:3 15:4 20:1 25:2 30:3 35:4 40:1 45:2 50:3 55:4 

# Numpy for Mathematics

## Fungsi Trigonomeri
NumPy memiliki fungsi trigonometri standar yang mengembalikan rasio trigonometri untuk sudut tertentu dalam radian.

In [89]:
a = np.array([0,30,45,60,90])

print('Nilai sin dari sudut yang berbeda-beda:')
# konversi radian dengan mengalikannya dengan pi/180
print(np.sin(a*np.pi/180))

print('Nilai kosinus sudut dalam array:')
print(np.cos(a*np.pi/180))

print('Nilai tangent sudut dalam array:')
print(np.tan(a*np.pi/180))

Nilai sin dari sudut yang berbeda-beda:
[0.         0.5        0.70710678 0.8660254  1.        ]
Nilai kosinus sudut dalam array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Nilai tangent sudut dalam array:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [90]:
a = np.array([0,30,45,60,90])

print('Array dengan nilai sinus:')
sin = np.sin(a*np.pi/180)
print(sin)

print('Hitung inverse (kebalikan) sinus dari sudut. Nilai yang dikembalikan dalam radian.')
inv = np.arcsin(sin)
print(inv)

print('Periksa hasil dengan mengonversi ke derajat:')
print(np.degrees(inv))


Array dengan nilai sinus:
[0.         0.5        0.70710678 0.8660254  1.        ]
Hitung inverse (kebalikan) sinus dari sudut. Nilai yang dikembalikan dalam radian.
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
Periksa hasil dengan mengonversi ke derajat:
[ 0. 30. 45. 60. 90.]


In [91]:
print('fungsi arccos dan arctan berperilaku serupa:')
cos = np.cos(a*np.pi/180)
print(cos)

print('Inverse dari cos:')
inv = np.arccos(cos)
print(inv)

print('dalam derajat:')
print(np.degrees(inv))

fungsi arccos dan arctan berperilaku serupa:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Inverse dari cos:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
dalam derajat:
[ 0. 30. 45. 60. 90.]


In [92]:
print('Fungsi Tan:')
tan = np.tan(a*np.pi/180)
print(tan)

print('Inverse dari tan:')
inv = np.arctan(tan)
print(inv)

print('dalam derajat:')
print(np.degrees(inv))

Fungsi Tan:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
Inverse dari tan:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
dalam derajat:
[ 0. 30. 45. 60. 90.]


## Fungsi Pembulatan dengan numpy.round
__numpy.around(a,decimals)__

In [93]:
a = np.array([1.0,5.55, 123, 0.567, 25.532])

print('Array asli:')
print(a)

print('Setelah pembulatan:')
print(np.around(a))
print(np.around(a, decimals = 1))


Array asli:
[  1.      5.55  123.      0.567  25.532]
Setelah pembulatan:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]


__np.floor__

Fungsi ini mengembalikan bilangan bulat terbesar yang tidak lebih besar dari parameter input. Dasar skalar x adalah bilangan bulat terbesar i, sehingga i <= x. Perhatikan bahwa dalam Python, floor selalu dibulatkan dari 0.

In [94]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10,12.9])

print('Array asli:')
print(a)

print('flooring array:')
print(np.floor(a))


Array asli:
[-1.7  1.5 -0.2  0.6 10.  12.9]
flooring array:
[-2.  1. -1.  0. 10. 12.]


__np.ceil__

Fungsi ceil() mengembalikan plafon nilai input, yaitu ceil skalar x adalah bilangan bulat terkecil i, sehingga i >= x.

In [95]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10,12.9])

print('Array asli:')
print(a)

print('ceiling array:')
print(np.ceil(a))

Array asli:
[-1.7  1.5 -0.2  0.6 10.  12.9]
ceiling array:
[-1.  2. -0.  1. 10. 13.]


## Operasi Aritmatika

Di dalam numpy ada fungsi untuk melakukan penjumlahan, pengurangan, perkalian dan pembagian

In [96]:
a = np.arange(9, dtype = np.float64).reshape(3,3)

print('Array pertama:')
print(a)

print('Array kedua:')
b = np.array([10,10,10])
print(b)

print('Penjumlahan 2 array:')
print(np.add(a,b))

print('Pengurangan 2 array:')
print(np.subtract(a,b))

print('Perkalian 2 array:')
print(np.multiply(a,b))

print('Pembagian 2 array:')
print(np.divide(a,b))

Array pertama:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Array kedua:
[10 10 10]
Penjumlahan 2 array:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
Pengurangan 2 array:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
Perkalian 2 array:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
Pembagian 2 array:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


### Operasi perkalian pangkat dengan numpy.power

In [97]:
a = np.array([10,100,1000])

print('Array asli:')
print(a)

print('Menggunakan power function:')
print(np.power(a,2))

print('Array kedua:')
b = np.array([1,2,3])
print(b)

print('Menggunakan power function lagi:')
print(np.power(a,b))


Array asli:
[  10  100 1000]
Menggunakan power function:
[    100   10000 1000000]
Array kedua:
[1 2 3]
Menggunakan power function lagi:
[        10      10000 1000000000]


Mengambil nilai sisa hasil bagi dengan np.mod/np.remainder

In [98]:
a = np.array([10,20,30])
b = np.array([3,5,7])

print('Array pertama:')
print(a)

print('Array kedua:')
print(b)

print('menggunakan mod() function:')
print(np.mod(a,b))

print('menggunakan remainder() function:')
print(np.remainder(a,b))


Array pertama:
[10 20 30]
Array kedua:
[3 5 7]
menggunakan mod() function:
[1 0 2]
menggunakan remainder() function:
[1 0 2]


# Fungsi Statistika

## Mencari nilai minimum dan maximum dalam suatu array

In [99]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])

print('Array asli:')
print(a)

print('menggunakan amin(1) function:')
print(np.amin(a,axis=1))

print('menggunakan amin(0) function lagi:')
print(np.amin(a,0))

print('menggunakan amax() function:')
print(np.amax(a))

print('menggunakan amin() function:')
print(np.amin(a))

print('menggunakan amax() function lagi:')
print(np.amax(a, axis = 0))

print('menggunakan amax() function lagi:')
print(np.amax(a, axis = 1))

Array asli:
[[3 7 5]
 [8 4 3]
 [2 4 9]]
menggunakan amin(1) function:
[3 3 2]
menggunakan amin(0) function lagi:
[2 4 3]
menggunakan amax() function:
9
menggunakan amin() function:
2
menggunakan amax() function lagi:
[8 7 9]
menggunakan amax() function lagi:
[7 8 9]


## Persentil

__np.percentile__

* Persentil (atau satu persentil) adalah ukuran yang digunakan dalam statistik yang menunjukkan nilai di bawah persentase pengamatan tertentu dalam kelompok pengamatan.

__numpy.percentile(a, q, axis)__\
a : Input array\
q : Persentil yang akan dihitung harus antara 0-100\
axis : sumbu

Persentil untuk nilai dalam kumpulan data tertentu dapat dihitung menggunakan rumus:

n = (P/100) x N


di mana N = jumlah nilai dalam kumpulan data, P = persentil, dan n = peringkat ordinal dari nilai yang diberikan (dengan nilai dalam kumpulan data diurutkan dari terkecil ke terbesar). Misalnya, ambil kelas yang terdiri dari 20 siswa yang memperoleh nilai berikut pada tes terbaru mereka: 75, 77, 78, 78, 80, 81, 81, 82, 83, 84, 84, 84, 85, 87, 87, 88, 88, 88, 89, 90. Skor ini dapat direpresentasikan sebagai kumpulan data dengan 20 nilai: {75, 77, 78, 78, 80, 81, 81, 82, 83, 84, 84, 84, 85, 87, 87, 88, 88, 88, 89, 90}.

Kita dapat menemukan skor yang menandai persentil ke-20 dengan memasukkan nilai yang diketahui ke dalam rumus dan menyelesaikan n:

n = (20/100) x 20

n = 4

Nilai keempat dalam kumpulan data adalah skor 78. Ini berarti bahwa 78 menandai persentil ke-20; dari siswa di kelas, 20 persen memperoleh skor 78 atau lebih rendah.

In [100]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])

print('Array asli:')
print(a)

print('menggunakan percentile() function:')
print(np.percentile(a,50))

print('Menggunakan percentile() function disumbu 1:')
print(np.percentile(a,50, axis = 1))

print('Menggunakan percentile() function disumbu 0:')
print(np.percentile(a,50, axis = 0))

Array asli:
[[30 40 70]
 [80 20 10]
 [50 90 60]]
menggunakan percentile() function:
50.0
Menggunakan percentile() function disumbu 1:
[40. 20. 60.]
Menggunakan percentile() function disumbu 0:
[50. 40. 60.]


## Median
Median didefinisikan sebagai nilai yang memisahkan bagian yang lebih tinggi dari sampel data dari bagian yang lebih rendah, dan bisa di hitung menggunakan __numpy.median__

In [101]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]])

print('Array asli:')
print(a)

print('menggunakan median() function:')
print(np.median(a))

print('menggunakan median() function sepanjang sumbu 0:')
print(np.median(a, axis = 0))

print('Menggunakan median() function sepanjang axis 1:')
print(np.median(a, axis = 1))


Array asli:
[[30 65 70]
 [80 95 10]
 [50 90 60]]
menggunakan median() function:
65.0
menggunakan median() function sepanjang sumbu 0:
[50. 90. 60.]
Menggunakan median() function sepanjang axis 1:
[65. 80. 60.]


## Mean
* Mean adalah jumlah elemen sepanjang sumbu dibagi dengan jumlah elemen. 
* Fungsi __numpy.mean()__ mengembalikan mean aritmatika elemen dalam array.
* Jika sumbu disebutkan secara eksplisit, maka akan dihitung berdasarkan nilai sumbunya

In [102]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

print('Array asli:')
print(a)

print('Menggunakan mean() function:')
print(np.mean(a))

print('Menggunakan mean() function sepanjang sumbu 0:')
print(np.mean(a, axis = 0))

print('Menggunakan mean() function sepanjang sumbu 1:')
print(np.mean(a, axis = 1))


Array asli:
[[1 2 3]
 [3 4 5]
 [4 5 6]]
Menggunakan mean() function:
3.6666666666666665
Menggunakan mean() function sepanjang sumbu 0:
[2.66666667 3.66666667 4.66666667]
Menggunakan mean() function sepanjang sumbu 1:
[2. 4. 5.]


## Weighted Average (Rata-Rata terbobot/tertimbang)
* Rata-rata tertimbang adalah rata-rata yang dihasilkan dari perkalian setiap komponen dengan faktor yang mencerminkan kepentingannya.
* Fungsi __numpy.average()__ menghitung rata-rata tertimbang elemen dalam array sesuai dengan bobot masing-masing yang diberikan dalam array lain.
* Fungsi dapat memiliki parameter sumbu.
* Jika sumbu tidak ditentukan, array diratakan.
* Mempertimbangkan array [1,2,3,4] dan bobot yang sesuai [4,3,2,1], rata-rata tertimbang dihitung dengan menambahkan produk dari elemen yang sesuai dan membagi jumlah dengan jumlah bobot.
* Rata-rata tertimbang = (1*4+2*3+3*2+4*1)/(4+3+2+1)

In [103]:
a = np.array([1,2,3,4])

print('Array asli:')
print(a)

print('menggunakan average() function:')
print(np.average(a))

print('menggunakan mean() function:')
print(np.mean(a))

# ini sama dengan mean ketika bobot tidak didefinisikan
wts = np.array([4,3,2,1])

print('menggunakan average() function lagi:')
print(np.average(a,weights = wts))

# Mengembalikan jumlah bobot, jika parameter yang dikembalikan disetel ke Benar
print('Jumlahan tertimbang')
print(np.average([1,2,3, 4],weights = [4,3,2,1], returned = True))


Array asli:
[1 2 3 4]
menggunakan average() function:
2.5
menggunakan mean() function:
2.5
menggunakan average() function lagi:
2.0
Jumlahan tertimbang
(np.float64(2.0), np.float64(10.0))


## Standar Deviasi
* Standar deviasi  adalah ukuran seberapa tersebar data dalam kaitannya dengan mean.
* Standar deviasi rendah berarti data mengelompok di sekitar rata-rata, dan standar deviasi tinggi menunjukkan data lebih tersebar.

In [104]:
np.std([1,2,3,4])

np.float64(1.118033988749895)

## Varians
* Varians adalah ukuran variabilitas.
* Ini dihitung dengan mengambil rata-rata deviasi kuadrat dari mean.
* Varians memberi tahu Anda tingkat penyebaran dalam kumpulan data Anda.
* Semakin menyebar data, semakin besar varians dalam kaitannya dengan mean

In [105]:
print(np.var([1,2,3,4]))

1.25


Standar deviasi mengukur seberapa jauh angka-angka dalam kumpulan data. Varians, di sisi lain, memberikan nilai aktual seberapa banyak angka dalam kumpulan data bervariasi dari rata-rata

# Thank You